#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : blockdiag
Version  : 1.5.3
Release  : 13
URL      : http://pypi.debian.net/blockdiag/blockdiag-1.5.3.tar.gz
Source0  : http://pypi.debian.net/blockdiag/blockdiag-1.5.3.tar.gz
Summary  : blockdiag generates block-diagram image from text
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: blockdiag-bin
Requires: blockdiag-python
Requires: Pillow
Requires: docutils
Requires: funcparserlib
Requires: nose
Requires: pep8
Requires: python-mock
Requires: reportlab
Requires: setuptools
Requires: webcolors
BuildRequires : Pillow-python
BuildRequires : docutils-python
BuildRequires : funcparserlib-python
BuildRequires : funcsigs-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pep8
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : reportlab-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : webcolors-python

%description
=====================
debian-logo-256color-palettealpha.png
--------------------------------------

%package bin
Summary: bin components for the blockdiag package.
Group: Binaries

%description bin
bin components for the blockdiag package.


%package python
Summary: python components for the blockdiag package.
Group: Default

%description python
python components for the blockdiag package.


%prep
%setup -q -n blockdiag-1.5.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503072951
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test || :
%install
export SOURCE_DATE_EPOCH=1503072951
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/blockdiag

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
